import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Header from "@/components/Header";
import Pokemonsearch from "@/components/Pokemon/Pokemonsearch";
import Pokemonlist from "@/components/Pokemon/Pokemonlist";
import Pokemonitem from "@/components/Pokemon/Pokemonitem";
import axios from "axios";
import { useEffect, useState } from "react";
export default function Home({ data }: any) {
  const [Pokemons, setPokemons] = useState<any | undefined>([]);

  useEffect(() => {
    setPokemons(data.results);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="pokedex " />
      <main className={styles.main}>
        <Pokemonsearch />
        <Pokemonlist>
          {Pokemons.map((Pokemon: any, index: any) => (
            <Pokemonitem name={Pokemon.name} url={Pokemon.url} key={index} />
          ))}
        </Pokemonlist>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { data } = await axios.get(
    "https://pokeapi.co/api/v2/pokemon/?offset=20&limit=20"
  );
  return {
    props: {
      data,
    }, // will be passed to the page component as props
  };
}
