import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Header from "@/components/Header";
import Pokemonsearch from "@/components/Pokemon/Pokemonsearch";
import Pokemonlist from "@/components/Pokemon/Pokemonlist";
import Pokemonitem from "@/components/Pokemon/Pokemonitem";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="pokedex " />
      <main className={styles.main}>
        <Pokemonsearch />
        <Pokemonlist>
          <Pokemonitem />
          <Pokemonitem />
          <Pokemonitem />
          <Pokemonitem />
        </Pokemonlist>
      </main>
    </>
  );
}
